import User from '../user/User';
import OrderLine from './OrderLine';
import Assignee from './Assignee';
import { Basket } from '../basket/Basket';
import ShippingManifest from '../../Models/delivery/ShippingManifest';

export default interface Order {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    pickingAt?: string;
    pickedAt?: string;
    packingAt?: string;
    packedAt?: string;
    placedAt?: string;
    onHoldPickingAt?: string;
    onHoldPackingAt?: string;
    dispatchedAt?: string;
    completedAt?: string;
    deletedAt?: string;
    shippingMethod?: string;
    shippingPreference?: string;
    notes?: string;
    currency?: string;
    billingPhone?: string;
    billingEmail?: string;
    billingFirstname?: string;
    billingLastname?: string;
    billingAddress?: string;
    billingAddressTwo?: string;
    billingAddressThree?: string;
    billingCity?: string;
    billingCounty?: string;
    billingState?: string;
    billingCountry?: string;
    billingZip?: string;
    shippingPhone?: string;
    shippingEmail?: string;
    shippingFirstname?: string;
    shippingLastname?: string;
    shippingAddress?: string;
    shippingAddressTwo?: string;
    shippingAddressThree?: string;
    shippingCity?: string;
    shippingCounty?: string;
    shippingState?: string;
    shippingCountry?: string;
    shippingZip?: string;
    contactEmail?: string;
    contactPhone?: string;
    trackingNo?: string;
    reference?: string;
    meta?: string;
    expectedDeliveryDate?: string;
    dispatchBy?: string;
    resourceType?: string;
    // relations
    basket?: Basket | null;
    user?: User | null;
    assignee?: Assignee | null;
    lines?: OrderLine[];
    shippingManifest?: ShippingManifest | null;
    // accessors
    isGift?: boolean;
    statusId?: number;
    deliveryMethod?: string;
    hasReusablePackagingOptIn?: boolean;
    tokensTotal?: number;
    onFirstOrder?: boolean;
    isFirstOrder?: boolean;
    weight?: number;
    isPastDueDispatch?: boolean;
    isPastDueDelivery?: boolean;
}
